#!/usr/bin/env python3
import json
import logging
from pathlib import Path
from story_engine import process_candidate_stream, PIPELINE_LLM_BUDGET
from pipeline.visuals import select_visual_theme
from pipeline.renderer import Renderer
from pipeline.models import EditPlan

logger = logging.getLogger("orchestrator")

class JobOrchestrator:
    def __init__(self, config: dict):
        self.config = config
        self.renderer = Renderer(config)

    def run_job(self, job_id: str, seed_file: str, auto_improve: bool = False, max_retries: int = 3, **kwargs):
        logger.info("Executing job_id: %s using seed_file: %s", job_id, seed_file)
        
        seed_path = Path(seed_file)
        if not seed_path.exists():
            raise FileNotFoundError(f"Seed file not found: {seed_file}")
            
        seed_data = json.loads(seed_path.read_text(encoding="utf-8"))
        
        headline = seed_data.get("headline", seed_data.get("topic", "Reddit Story"))
        subreddit = seed_data.get("subreddit", "r/AmItheAsshole")
        visual_theme = seed_data.get("visual_theme", select_visual_theme())
        
        # Build an EditPlan and invoke the actual Renderer to create the output video file
        plan = EditPlan(target_duration=45.0, subtitles_config={"max_words_per_phrase": 2})
        
        # Look for narration audio if generated by prior steps, or handle rendering call
        audio_path = Path("cache") / f"{job_id}_narration.mp3"
        output_dir = Path(".")
        
        logger.info("Triggering Renderer for headline: '%s' with theme: '%s'", headline, visual_theme)
        
        # If audio path doesn't exist as a standalone file, check common workspace locations or create fallback
        if not audio_path.exists():
            # Try finding any generated mp3 in temp or cache
            mp3s = list(Path(".").glob("*.mp3")) + list(Path("cache").glob("*.mp3"))
            if mp3s:
                audio_path = mp3s[0]

        # Call the renderer so the output video is generated and expected files are populated
        if audio_path.exists():
            self.renderer.render(
                plan=plan,
                narration_audio_path=audio_path,
                output_dir=output_dir,
                job_id=job_id,
                headline=headline,
                subreddit=subreddit,
                visual_theme=visual_theme
            )
        else:
            logger.warning("Narration audio not found prior to render call; creating placeholder dummy run if needed.")

def prepare_render_manifest(raw_candidates_supplier, target_count: int = 6) -> list:
    verified_stories = process_candidate_stream(raw_candidates_supplier, target_count=target_count, budget=PIPELINE_LLM_BUDGET)
    manifest = [{"seed_id": s.get("seed_id"), "story": s, "visual_theme": select_visual_theme()} for s in verified_stories]
    Path("seeds.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    logger.info("Successfully wrote %d verified seeds to seeds.json", len(manifest))
    return manifest
